title: Lab Manual
description: YOUR DESCRIPTION
baseurl: 'our_domain'
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-default-layout
theme: jekyll-theme-minimal
# Navigation
# List links that should appear in the site sidebar here
navigation:
  - text: Documentation
    internal: true
    url: ./docs


sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development
